apiVersion: v1
kind: Namespace
metadata:
  name: exp4

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: exp4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: nginx
          image: app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: exp4
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

